version: '3.9'

services:
  database:
   image: postgres
   container_name: tutorial
   restart: always
   ports:
   - 8080:8080
   enviroment:
   -POSTGRES_USER=admin
   -POSTGRES_PASSWORD=admin
   -POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:  
 pgdata:
  driver: local
